### ISSUE TITLE
ffmpeg binary is'nt created

### ISSUE THREAD

**Issue by eldiago** [id3as/ffmpeg-libvpx-HDR-static#1]
I've run the mentioned CL# successfully, but ffmpeg binary isn't installed. I am using fedora 25 (64 bit)

**Comment by dom-robinson** [comment]
The script deliberately doesn't install it. 

If you see "ffmpeg binary successfully built with these components" at the end then it is in the directory you ran the script. 

If you want it "installed" then you should copy it to somewhere on your path.

Hope that helps - although by and large we don't provide support on this.
